# Blind cross-family label check. Item generated by family A is labelled by family B (other family), fallback Cohere.
import sys, json, re, concurrent.futures as cf
sys.path.insert(0,'/workspace/maclaw_reranker/scripts'); import llmc
from gen import JUDGE, J, D
def ask(gen, sys_, user):
    for spec in JUDGE[gen]:
        try:
            c,m,dt=llmc.chat(spec,[{'role':'system','content':sys_},{'role':'user','content':user}],temperature=0,max_tokens=2500,timeout=120,retries=1)
            return J(c), spec
        except Exception as e:
            print('judge err',spec,str(e)[:80],file=sys.stderr)
    return None, None
def topic_batch(b):
    sys_=("You label data for a topic-switch detector. For each item decide if the NEW user message continues the same topic/task as the conversation history ('same') or switches to an unrelated topic/task ('new'). Return ONLY JSON {\"labels\":[\"same\"|\"new\", ...]} in item order.")
    u='\n\n'.join(f"Item {k+1}\nHistory: "+' || '.join(r['history'])+f"\nAssistant: {r.get('assistant_last','')}\nNEW: {r['new']}" for k,r in enumerate(b))
    return sys_,u,'labels'
def int_batch(b):
    sys_=("You label data for an AI agent interrupt handler. The agent is executing TASK; the user sends MESSAGE mid-task. 'related' = the message supplements, corrects, constrains or modifies TASK; 'unrelated' = it is a separate new request or question. Return ONLY JSON {\"labels\":[\"related\"|\"unrelated\", ...]} in item order.")
    u='\n\n'.join(f"Item {k+1}\nTASK: {r['task']}\nMESSAGE: {r['message']}" for k,r in enumerate(b))
    return sys_,u,'labels'
C=None
def cod_batch(b):
    cat='\n'.join(f"- {c['name']}: {c['description']}" for c in C)
    sys_=("You select skills for a coding sub-agent. For each task, list the catalogue names that are genuinely useful (1-3 names, most useful first). Return ONLY JSON {\"labels\":[[\"name\",...], ...]} in task order.")
    u=f"Catalogue:\n{cat}\n\n"+'\n'.join(f"Task {k+1}: {r['task']}" for k,r in enumerate(b))
    return sys_,u,'labels'
def run(kind):
    global C
    rows=[json.loads(l) for l in open(f'{D}/{kind}_raw.jsonl')]
    mk={'topic':topic_batch,'interrupt':int_batch,'coding':cod_batch}[kind]
    if kind=='coding': C=json.load(open(f'{D}/coding_cands.json'))
    batches=[]
    for g in set(r['gen'] for r in rows):
        rs=[r for r in rows if r['gen']==g]
        batches+=[rs[i:i+10] for i in range(0,len(rs),10)]
    def do(b):
        s,u,key=mk(b); res,spec=ask(b[0]['gen'],s,u)
        if not res or len(res.get(key,[]))!=len(b): return []
        out=[]
        for r,l in zip(b,res[key]): r=dict(r); r['judge']=spec; r['judge_label']=l; out.append(r)
        return out
    allr=[]
    with cf.ThreadPoolExecutor(6) as ex:
        for o in ex.map(do,batches): allr+=o
    keep=[]
    for r in allr:
        if kind=='coding':
            jl=[n for n in r['judge_label'] if isinstance(n,str)]
            gold=[n for n in r['relevant'] if n in jl]
            if gold: r['gold']=gold; keep.append(r)
        elif r['judge_label']==r['label']: keep.append(r)
    with open(f'{D}/{kind}.jsonl','w') as f:
        for r in keep: f.write(json.dumps(r,ensure_ascii=False)+'\n')
    print(kind,'raw',len(rows),'judged',len(allr),'agreed',len(keep))
if __name__=='__main__': run(sys.argv[1])
